modLoader = "javafml"
loaderVersion = "${forge_loader_version}"
issueTrackerURL = "${issue_tracker_url}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${repository_url}"
authors = "${authors}"
description = '''${description}'''
logoFile = "${mod_id}.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_forge}"
ordering = "NONE"
side = "BOTH"

